# -*- coding: utf-8 -*-
"""Sales_transactions_PCA_UMAP_K-Means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFaHH36vo3GG-aAV-wWdbHSQDPYgiGGM
"""

pip install umap-learn

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import plotly.graph_objs as go
import plotly.figure_factory as ff
import umap
from sklearn.cluster import KMeans

data = pd.read_csv ('/content/Sales_Transactions_Dataset_Weekly.csv')
data  = data.iloc[:,:53]
print(data.head())
data.shape
data.info()
data.describe()

# defining feature set
X = data.drop(['Product_Code'], axis = 1)
print(type(X))
print(X.shape)

#normalizing numerical features so that each fetaure has mean 0 and variance 1
scalar = StandardScaler()
X_scaled = scalar.fit_transform(X)

#Implementing PCA  to visualize dataset
pca = PCA(n_components= 2)
pca.fit(X_scaled)
x_pca = pca.transform(X_scaled)
print("Variance explained by each of the n_components: ", pca.explained_variance_ratio_)
print("Total variance explained by n_components:  ", pca.explained_variance_ratio_.sum())

products = list(data['Product_Code'])

dataset = [go.Scatter(x = x_pca[:,0], y = x_pca[:,1], mode = 'markers',
                      marker = dict(color = None, colorscale = 'Rainbow', opacity = 0.5),
                        text = [f"Product : {a} " for a in products ],
                        hoverinfo= 'text')]


layout = go.Layout( title = "PCA Dimesnionality Reduction", width = 700, height = 700,
                   xaxis = dict( title = 'First Dimension'),
                   yaxis = dict (title  = 'Second Dimension'))
fig = go.Figure(data = dataset, layout = layout)
fig.show()

# Implementing UMAP to visualize the data

u = umap.UMAP(n_components = 2, n_neighbors = 10, min_dist = 0.1)
x_umap = u.fit_transform(X_scaled)

dataset = [go.Scatter(x = x_umap[:,0], y = x_umap[:,1], mode = 'markers',
                      marker = dict(color = None, colorscale = 'Rainbow', opacity = 0.5),
                        text = [f"Product : {a} " for a in products ],
                        hoverinfo= 'text')]


layout = go.Layout( title = "UMAP Dimesnionality Reduction", width = 700, height = 700,
                   xaxis = dict( title = 'First Dimension'),
                   yaxis = dict (title  = 'Second Dimension'))
fig = go.Figure(data = dataset, layout = layout)
fig.show()

# Labelling cluster using KMeans
kmeans = KMeans(n_clusters = 5)
kmeans.fit(x_umap)

labels = list(kmeans.labels_)
dataset = [go.Scatter(x = x_umap[:,0], y = x_umap[:,1], mode = 'markers',
                      marker = dict(color = kmeans.labels_, colorscale = 'Rainbow', opacity = 0.5),
                        text = [f"Product : {a}<br>Label :{b} " for a,b in list (zip(products,labels))],
                        hoverinfo= 'text')]


layout = go.Layout( title = "UMAP Dimesnionality Reduction", width = 700, height = 700,
                   xaxis = dict( title = 'First Dimension'),
                   yaxis = dict (title  = 'Second Dimension'))
fig = go.Figure(data = dataset, layout = layout)
fig.show()

data['Label'] = kmeans.labels_
print(data.Label.value_counts())

